from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any, Literal

from api.annotations import AnnotationRegistry, FileBuildCtx
from parser_schemas import ANNOTATION_PREFIX

type Environment = Literal['server', 'client', 'shared']
FILENAMES = ['*.lua', '*.luau']

AUTOGENERATED_HEADER = 'Generated using lua-anot; do not edit manually.'

@dataclass
class BuildException(Exception):
    message: str
    file: Path
    workdir: Path

    def __post_init__(self):
        super().__init__(self.message)

@dataclass
class ProcessCtx():
    reg: AnnotationRegistry
    workdir: Path
    workspace: Workspace

    def error(self, message: str, file: Path):
        raise BuildException(message, file, self.workdir)

type BuildCtxList = dict[Environment, BuildProcessCtx]

@dataclass
class PostProcessCtx(ProcessCtx):
    build_ctxs: BuildCtxList

    def create_file(self, env: Environment, name: str, text: str):
        self.build_ctxs[env].create_file(name, text)

    def dump_json(self, env: Environment, name: str, data: dict[Any, Any]):
        out = {'_comment': AUTOGENERATED_HEADER} | data
        self.create_file(env, name, json.dumps(out, indent=4))

@dataclass
class BuildProcessCtx(ProcessCtx):
    output_root: Path
    env: Environment

    def create_file(self, name: str, text: str):
        file = self.output_root / name
        file.parent.mkdir(parents=True, exist_ok=True)
        file.write_text(text)
        
        return file

    def process_file(self, file: Path):
        from parser import FileParser

        with file.open('r') as f:
            text = f.read()
            if ANNOTATION_PREFIX in text:
                parser = FileParser(self.reg, file, self)
                parser.parse(text)

                #post-file
                for hook in self.reg.file_build_hooks:
                    hook(FileBuildCtx(self, parser, file))

                return parser

    def process_dir(self):
        for filename in FILENAMES:
            matched_files = self.workdir.rglob(filename)
            for file in matched_files:
                self.process_file(file)


type Workspace = dict[Environment, Path]
class Config():
    def __init__(self, data: dict[Any, Any]):
        self.out_dir_name = data.get('outDirName', 'Generated')

        #convert each path string to a path object
        self.workspaces: list[Workspace] = [
            {env: Path(path) for env, path in wksp.items()}
            for wksp in data.get('workspaces', [])
        ]