from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any, Literal
from importlib.resources import files

from lua_annotations.annotation_meta_parse import META_FILE_NAME, AnnotationMeta

from .exceptions import BuildError
from .api.annotations import FileBuildCtx, SortedRegistry
from .parser_schemas import ANNOTATION_PREFIX

type Environment = Literal['server', 'client', 'shared']
FILENAMES = ['.lua', '.luau']

AUTOGENERATED_HEADER = 'Generated using lua-anot; do not edit manually.'


def get_template(name: str):
    root = files('lua_annotations')
    path = root / 'templates' / name
    return path.read_text()


@dataclass
class FileBuildError(BuildError):
    message: str
    file: Path
    workdir: Path

    def __post_init__(self):
        super().__init__(self.message)


@dataclass
class ProcessCtx:
    reg: SortedRegistry
    root_dir: Path
    workspace: Workspace

    def error(self, message: str, file: Path):
        raise FileBuildError(message, file, self.root_dir)


type BuildCtxList = dict[Environment, BuildProcessCtx]


@dataclass
class PostProcessCtx(ProcessCtx):
    build_ctxs: BuildCtxList

    def create_file(self, env: Environment, name: str, text: str):
        self.build_ctxs[env].create_file(name, text)

    def dump_json(self, env: Environment, name: str, data: dict[Any, Any]):
        out = {'_comment': AUTOGENERATED_HEADER} | data
        self.create_file(env, name, json.dumps(out, indent=4))


@dataclass
class BuildProcessCtx(ProcessCtx):
    workdirs: dict[Path, str]
    output_root: Path
    env: Environment

    def create_file(self, name: str, text: str):
        file = self.output_root / name
        file.parent.mkdir(parents=True, exist_ok=True)
        file.write_text(text)

        return file
    

    def process_file(self, file: Path, meta: AnnotationMeta | None = None):
        from .parser import FileParser

        with file.open('r') as f:
            text = f.read()

            # meta proc
            if meta:
                text = meta.process(text)

            if ANNOTATION_PREFIX in text:
                parser = FileParser(self.reg, file, self)
                parser.parse(text)

                # post-file
                for hook in self.reg.file_build_hooks:
                    hook(FileBuildCtx(self, parser, file))

                return parser


    def process_dir(self, dir: Path):
        meta_file = dir / META_FILE_NAME

        meta = None
        if meta_file.exists():
            meta = AnnotationMeta(meta_file)

        for file in dir.iterdir():            
            if file.is_dir():
                self.process_dir(file)

            elif file.suffix in FILENAMES:
                self.process_file(file, meta)


type Workspace = dict[Environment, dict[Path, str]]
