from dataclasses import dataclass, field
from pathlib import PurePath
from typing import Any, Protocol, runtime_checkable

from .annotations import ENVIRONMENTS
from lua_annotations.build_process import AUTOGENERATED_HEADER, Environment, ProcessCtx, Workspace

HEADER = '-- ' + AUTOGENERATED_HEADER

ENV_TO_IMPORT: dict[Environment, str] = {
    'server': 'game:GetService("ServerScriptService")',
    'client': 'game:GetService("Players").LocalPlayer:FindFirstChildOfClass("PlayerScripts")',
    'shared': 'game:GetService("ReplicatedStorage")'
}
ENV_TO_VAR: dict[Environment, str] = {
    'server': 'ServerScriptService',
    'client': 'PlayerScripts',
    'shared': 'ReplicatedStorage'
}
INDENT = ' ' * 4


@runtime_checkable
class SupportsAsDict(Protocol):
    def asdict(self) -> dict[Any, Any]:
        ...


def convert_dict(resolver: LuaPathResolver, data: Any, indent: int = 0, sep: str = ' = ', prefix: str = 'return'):
    def table_block(entry_lines: list[str], level: int) -> str:
        if len(entry_lines) == 0:
            return '{}'
        inner = INDENT * (level + 1)
        outer = INDENT * level
        return '\n'.join(
            ['{', *(f'{inner}{line}' for line in entry_lines), f'{outer}}}']
        )

    def process_dict(value: dict[Any,Any], level: int):
        entries = [
            f'{key_to_lua(k, level)}{sep}{to_lua(v, level + 1)},'
            for k, v in value.items()
        ]
        return table_block(entries, level)


    def to_lua(value: Any, level: int):
        if isinstance(value, LuaExpr):
            return value.string

        if isinstance(value, LuaPath):
            return value.to_lua(resolver)

        if isinstance(value, SupportsAsDict):
            return process_dict(value.asdict(), level)

        if isinstance(value, dict):
            return process_dict(value, level)

        if isinstance(value, (list, tuple)):
            entries = [f'{to_lua(item, level + 1)},' for item in value]
            return table_block(entries, level)

        if isinstance(value, str):
            escaped = value.replace('\\', '\\\\').replace('"', '\\"')
            return f'"{escaped}"'

        if isinstance(value, bool):
            return 'true' if value else 'false'

        if value is None:
            return 'nil'

        return str(value)

    def key_to_lua(key: Any, level: int):
        if isinstance(key, str) and key.isidentifier():
            return key
        return f'[{to_lua(key, level)}]'

    body = to_lua(data, indent)
    import_lines = resolver.get_import_lines()

    parts: list[str] = []
    if import_lines:
        parts += ['\n'.join(import_lines), '']
    parts.append(f'{prefix} {body}')

    return '\n'.join(parts) + '\n'


class LuaPathResolver:
    """Resolves lua paths and stores required imports; one should be created per output file."""
    def __init__(self, workspace: Workspace):
        self.workspace = workspace
        self.used_imports: set[Environment] = set()

    def _resolve_expr(self, env: Environment, raw_expr: str, inline_require: bool = False):
        map = ENV_TO_IMPORT if inline_require else ENV_TO_VAR
        #require(:Packages.default_extension): -> require(ServerScriptService.Packages.default_extension).example.path)
        return raw_expr.replace(':', f'{map[env]}.', 1)

    def normalize(self, path: PurePath, inline_require: bool = False) -> tuple[Environment, PurePath, str]:
        # path is relative an env workdir
        for env, path_map in self.workspace.items():
            for workdir, lua_expr in path_map.items():
                try:
                    relative = path.relative_to(workdir)
                    return env, relative, self._resolve_expr(env, lua_expr, inline_require)
                except ValueError:
                    continue

        # path is prefixed with an env name
        parts = [part for part in path.parts if part not in ('', '.', '/')]
        if parts and parts[0] in self.workspace:
            env = parts[0]  # type: ignore[assignment]
            return env, PurePath(*parts[1:]), ENV_TO_VAR[env]

        raise ValueError(f'Unknown lua path: {path}')

    def mark_used(self, env: Environment) -> None:
        self.used_imports.add(env)

    def get_import_lines(self) -> list[str]:
        import_lines: list[str] = []

        for env in ENVIRONMENTS:
            if env in self.used_imports:
                import_lines.append(f'local {ENV_TO_VAR[env]} = {ENV_TO_IMPORT[env]}')

        return import_lines


@dataclass
class LuaExpr:
    """Tiny wrapper class to represent a lua expression literal.
    When used with the `convert_dict` api, the value is not wrapped with quotes in the lua output."""
    string: str


@dataclass
class LuaPath:
    """A class which allows for easy conversion of a pathlib path into a lua expression. Note that any non-relative paths require a LuaPathResolver."""
    path: PurePath
    relative: bool=False
    require: bool=False
    properties: list[str]=field(default_factory=list)
    function: bool=False

    def _parts_no_ext(self, p: PurePath):
        return [x for x in p.with_suffix('').parts if x not in ('', '.')]

    def _post_process(self, string: str):
        if self.require or len(self.properties) > 0:
            string = f'require({string})'
        
        for prop in self.properties:
            string += '.' + prop

        string = string.replace('..', '.')

        if self.function or (len(self.properties) > 0 and not self.require):
            #if require is false, wrap the require path in a function
            return f'function() return {string} end'
        
        return string

    def to_lua_relative(self):
        assert self.relative

        #relative path (script.Parent.Example.Path)
        parts = self._parts_no_ext(self.path)
        expr = '.'.join(['script', 'Parent', *parts])
        return self._post_process(expr)

    def to_lua(self, resolver: LuaPathResolver, inline_require: bool = False):
        if self.relative:
            return self.to_lua_relative()

        #env path (ReplicatedStorage.Example.Path)
        env, rel, expr_root = resolver.normalize(self.path, inline_require)
        if not inline_require:
            resolver.mark_used(env)

        parts = self._parts_no_ext(rel)
        expr = '.'.join([expr_root, *parts])
        return self._post_process(expr)


#public api
def convert_dict_module(ctx: ProcessCtx, data: Any, indent: int = 0):
    dict_str = convert_dict(LuaPathResolver(ctx.workspace), data, indent)
    return f'{HEADER}\n{dict_str}'

def convert_dict_type(ctx: ProcessCtx, data: dict[str, Any], type_name: str, indent: int = 0):
    dict_str = convert_dict(LuaPathResolver(ctx.workspace), data, indent, sep=': ', prefix = f'export type {type_name} = ')
    return f'{HEADER}\n{dict_str}'
