from dataclasses import dataclass
from pathlib import Path, PurePath
from typing import Any

from api.annotations import ENVIRONMENTS
from build_process import AUTOGENERATED_HEADER, Environment, PostProcessCtx

HEADER = '-- ' + AUTOGENERATED_HEADER

ENV_TO_IMPORT: dict[Environment, str] = {
    'server': 'game:GetService("ServerScriptService")',
    'client': 'game:GetService("Players").LocalPlayer.PlayerScripts',
    'shared': 'game:GetService("ReplicatedStorage")'
}
ENV_TO_VAR: dict[Environment, str] = {
    'server': 'ServerScriptService',
    'client': 'PlayerScripts',
    'shared': 'ReplicatedStorage'
}


class LuaPathResolver:
    def __init__(self, ctx: PostProcessCtx):
        self.env_map: dict[Environment, Path] = {k: v.workdir for k, v in ctx.build_ctxs.items()}
        self.used_imports: set[Environment] = set()

    def normalize(self, path: PurePath) -> tuple[Environment, PurePath]:
        # path is relative an env workdir
        for env, workdir in self.env_map.items():
            try:
                relative = path.relative_to(workdir)
                return env, relative
            except ValueError:
                continue

        # path is prefixed with an env name
        parts = [part for part in path.parts if part not in ('', '.', '/')]
        if parts and parts[0] in self.env_map:
            env = parts[0]  # type: ignore[assignment]
            return env, PurePath(*parts[1:])

        raise ValueError(f'Unknown lua path: {path}')

    def mark_used(self, env: Environment) -> None:
        self.used_imports.add(env)

    def convert_dict(self, dict: dict[Any, Any]):
        return _LuaDict(self, dict).out

    def get_import_lines(self):
        import_lines: list[str] = []

        for env in ENVIRONMENTS:
            if env in self.used_imports:
                import_lines.append(f'local {ENV_TO_VAR[env]} = {ENV_TO_IMPORT[env]}')

        return import_lines


@dataclass
class LuaPath:
    path: PurePath
    relative: bool=False
    require: bool=False

    def to_lua(self, resolver: LuaPathResolver):
        string = self._to_lua(resolver)
        if self.require:
            string = f'require({string})'
        return string

    def _to_lua(self, resolver: LuaPathResolver):
        #relative path (script.Parent.Example.Path)
        if self.relative:
            path_no_ext = self.path.with_suffix('')
            parts = [part for part in path_no_ext.parts if part not in ('.', '')]
            return '.'.join(['script', 'Parent', *parts])

        #env path (ReplicatedStorage.Example.Path)
        env, relative = resolver.normalize(self.path)
        resolver.mark_used(env)

        module_name = relative.with_suffix('')
        module_parts = [part for part in module_name.parts if part not in ('', '.')]
        return '.'.join([ENV_TO_VAR[env], *module_parts])


class _LuaDict:
    def __init__(self, resolver: LuaPathResolver, dict: dict[Any, Any]):
        self.dict = dict
        self.resolver = resolver

        self.out = self._convert()

    def _key_to_lua(self, key: Any):
        if isinstance(key, str) and key.isidentifier():
            return key
        return f'[{self._value_to_lua(key, 0)}]'

    def _value_to_lua(self, value: Any, indent: int):
        if isinstance(value, LuaPath):
            return value.to_lua(self.resolver)

        elif isinstance(value, dict):
            inner_indent = ' ' * 4 * (indent + 1)
            outer_indent = ' ' * 4 * indent
            lines = ['{']

            for key, val in value.items():
                lines.append(f'{inner_indent}{self._key_to_lua(key)} = {self._value_to_lua(val, indent + 1)},')

            lines.append(f'{outer_indent}}}')
            return '\n'.join(lines)

        elif isinstance(value, str):
            escaped = value.replace('\\', '\\\\').replace('"', '\\"')
            return f'"{escaped}"'

        elif isinstance(value, bool):
            return 'true' if value else 'false'

        elif value is None:
            return 'nil'

        return str(value)

    def _convert(self):
        body = self._value_to_lua(self.dict, 0)
        import_lines = self.resolver.get_import_lines()

        lines = [HEADER]
        if import_lines:
            lines.append('\n'.join(import_lines))
            lines.append('')

        lines.append(f'return {body}')
        return '\n'.join(lines) + '\n'


def convert_dict(ctx: PostProcessCtx, dict: dict[Any, Any]):
    return _LuaDict(LuaPathResolver(ctx), dict).out